function clearBuildingLevel2Objects(bldg)
%CLEARBUILDINGLEVEL2OBJECTS Method to remove all Level2Objs from the 
% corresponding Building.
%   This method is a helper method to remove every Level2 Object from the
%   Building in question.

%% Arguments Block
% Validate input arguments.
arguments
    % site: Self-referential Building object.
    bldg (1,1) ece.Building

end %argblock

%% Remove Objects from Building Array
% Remove specified objects from the Building.
% -- Remove AirMovers
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.AirMover,...
    1:length(bldg.Airmovers));

% -- Remove Appliances
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.Appliance,...
    1:length(bldg.Appliances));

% -- Remove BelowGradeSurfaces
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.BelowGradeSurface,...
    1:length(bldg.BelowGradeSurfaces));

% -- Remove DHWPipesMechRooms
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.DHWPipesMechRoom,...
    1:length(bldg.DHWpipesMechRoom));

% -- Remove DHWSystem
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.DHWSystem,...
    1:length(bldg.DHWsystems));

% -- Remove DHWTank
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.DHWTank,...
    1:length(bldg.DHWtanks));

% -- Remove Glazed Surfaces
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.Glazing,...
    1:length(bldg.GlazedSurfaces));

% -- Remove HeatCool
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.HeatCool,...
    1:length(bldg.HeatCool));

% -- Remove Opaque Surfaces
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.OpaqueSurface,...
    1:length(bldg.OpaqueSurfaces));

% -- Remove Plumbing Fixtures
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.PlumbingFixture,...
    1:length(bldg.PlumbingFixtures));

% -- Remove Pump
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.Pump,...
    1:length(bldg.Pumps));

% -- Remove Slabs On Grade
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.SlabOnGrade,...
    1:length(bldg.SlabOnGrade));

% -- Remove Spaces
bldg.removeLevel2Objects(...
    ece.enum.Level2ObjectType.Space,...
    1:length(bldg.Spaces));

end %function

